name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.7"

      # Step 3: Initialize Terraform 
      - name: Terraform Init
        run: terraform init

      # Step 4: Check Terraform formatting
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Step 5: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
