name: Terraform Checks

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform fmt and validate
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the pull request
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Run `terraform fmt` to auto-format the files
      - name: Terraform Format Check and Auto-fix
        run: terraform fmt -recursive

      # Run `terraform validate` to validate the configuration
      - name: Terraform Validate
        run: terraform validate
